### ISSUE TITLE
Time controls for messages

### ISSUE THREAD

**Issue by jimbokimbo** [jdw353/google-workspace-apps-script-toolbox#3]
Is there a way to set a time window for when the bot publishes messages in Google Chat and when it does not? No one want's to be pinged at 3 am in the morning by a bot. So having a way to set the bot up so it only sends/publishes messages between the hours of 9 am to 5 pm (for example) would be really handy.

**Comment by jdw353** [comment]
Great suggestion! Applied this update in the [latest update](https://github.com/jdw353/google-workspace-apps-script-toolbox/commit/87ac349515171517dd6a0208e84e55ed4e1891cf#diff-7c75cd336d5a4f8a12f880ca8490b6a75274e6e430661dc00d22a06d291c720d).

**Comment by jimbokimbo** [comment]
Seems to be publishing out of hours? Left the hours set as in the code START: 9,  END: 17 however had the bot fired after 17.

**Comment by jdw353** [comment]
Can you run the executeUpdateWorkflow after hours and see what the debug statement says? I suspect your script timezone may not be what you expect it to be (which you can check in the script's manifest).

**Comment by jimbokimbo** [comment]
Thanks for the quick reply. On the Execution log, I am getting:

"Info	Europe/London: valid day (true), valid hour (false)"

which is the correct timezone.

On the scripts manifest I am seeing:

`{
  "timeZone": "Europe/London",
  "dependencies": {
  },
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8"
}`

**Comment by jdw353** [comment]
If that's the debug log, the script exits after that logger is fired. You shouldn't see it polling for new posts. If that's the case I wonder if it was just a lag on the border of the time slot.

**Comment by jimbokimbo** [comment]
I'll keep an eye on it. We have it running in multiple rooms (separate script for each room) the first one posted 17:40 and the last room got a post at 18:21. The blog post that they posted was published at 17:36.

**Comment by jdw353** [comment]
Okay, keep an eye on it. If the logic is working now and the updates were put in properly, then it shouldn't be firing. Please check and make sure all new code was moved into the other scripts.

**Comment by jdw353** [comment]
Found the issue. Trigger execution passes an object into the target function, which was falsely enabling the init flag. I've corrected this and now it should work as expected. Great call out!

**Comment by jimbokimbo** [comment]
Thanks.
