### ISSUE TITLE
Requested Scopes section is out of date

### ISSUE THREAD

**Issue by switch1280** [jdw353/google-workspace-apps-script-toolbox#5]
The Requested Scopes section of the Readme needs to be updated as it is no longer valid.

**Comment by jdw353** [comment]
Can you be more specific on which tool has scopes that are out of date?

**Comment by switch1280** [comment]
Google Chat Updates Bot.

**Comment by switch1280** [comment]
![30402093-3368-4267-A74F-178F3F574C5C](https://user-images.githubusercontent.com/26970070/222928234-fb392976-c165-48db-ab59-892e727dcd8b.png)

these links…

**Comment by jdw353** [comment]
I just tested and both scopes are still required. Where are you seeing
otherwise?

**Comment by switch1280** [comment]
When I click on the links, I get this.
![7C6E20B3-99CE-4322-88E2-6BB674C0AB60](https://user-images.githubusercontent.com/26970070/222928892-36b6b2bb-48bf-4503-8730-19fbd05d47d2.png)

**Comment by jdw353** [comment]
It actually appears that that message is incorrect. My guess is that they forgot to document these scopes on that page. If you look in your deployment of the Chat app, you'll see that these scopes are still listed as being used. I'll file a bug with the documentation team to make sure this is cleaned up.
![Screenshot 2023-03-04 182042](https://user-images.githubusercontent.com/4503940/222933097-a6db85af-0cc9-4bb2-8cc9-d64154bf7e7e.png)
